# This is a basic workflow to help you get started with Actions

name: AzurePowerShellTesting

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: 'Azure PowerShell script: InlineScript'
      continue-on-error: true
      uses: Azure/login@v1
      with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"
    - name: 'Azure PowerShell script: InlineScript'
      continue-on-error: true
      uses: azure/powershell@v1
      with:
        inlineScript: |-
          Write-Host "Testing 1.2..3..."
          Get-ChildItem
        errorActionPreference: Stop
        failOnStandardError: false
        azPSVersion: 6.1.0
    - name: Run a multi-line script
      run: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
