# This is a basic workflow that is manually triggered

name: VSTest Functional Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'VSTest Step'
        uses: microsoft/vstest-action@main
        with:
            testAssembly: '**\$(BuildConfiguration)\*test*.dll;-:**\obj\**'
            searchFolder: ./tests/
